version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gamestore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  springboot-app:
#    build: .
#    container_name: gamestore
#    volumes:
#      - ./target/myapp.jar:/app/app.jar
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
volumes:
  postgres_data: