version: '3.9'

services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis-verification
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: new_secret
      POSTGRES_DB: gamestore
    ports:
      - "5433:5432"
    volumes:
      - lever_db:/var/lib/postgresql/data
#  springboot-app:
#    build: .
#    container_name: gamestore
#    volumes:
#      - ./target/myapp.jar:/app/app.jar
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
volumes:
  lever_db:
  redis_data: